/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorytracker;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author jampa
 */
public class InventoryGUI extends javax.swing.JFrame {

    AddToInv add;
    ViewInv view;
    ChangeInv change;
    HashMap<String, ArrayList<String[]>> localData = new HashMap<>();
    /**
     * Creates new form InventoryGUI
     */
    public InventoryGUI() throws SQLException {
        initComponents();
        add = new AddToInv();
        view = new ViewInv();
        change = new ChangeInv();
        
        //add.addItemType("Misc", "No description declared");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable_log = new javax.swing.JTable();
        jTable_log.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    jButton_clearLog.setEnabled(jTable_log.getSelectedRows().length != 0);
                }
            }});
            jPanel_Quantities = new javax.swing.JPanel();
            jLabel5 = new javax.swing.JLabel();
            jButton_clearLog = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            jButton2 = new javax.swing.JButton();
            jPanel4 = new javax.swing.JPanel();
            jPanel_modify = new javax.swing.JPanel();
            jButton_refresh = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jScrollPane2 = new javax.swing.JScrollPane();
            jTextArea2 = new javax.swing.JTextArea();
            jPanel_add = new javax.swing.JPanel();
            jPanel5 = new javax.swing.JPanel();
            jButton_AddItemType = new javax.swing.JButton();
            jTextField_addItemTypeDescription = new javax.swing.JTextField();
            jLabel11 = new javax.swing.JLabel();
            jTextField_addItemTypeName = new javax.swing.JTextField();
            jLabel10 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            jSeparator1 = new javax.swing.JSeparator();
            jPanel_AddItem = new javax.swing.JPanel();
            jScrollPane5 = new javax.swing.JScrollPane();
            jTable_AddValues = new javax.swing.JTable();
            jButtton_AddItem = new javax.swing.JButton();
            jLabel13 = new javax.swing.JLabel();
            jSeparator2 = new javax.swing.JSeparator();
            jPanel6 = new javax.swing.JPanel();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTextArea1 = new javax.swing.JTextArea();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jTable_log.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Date", "Log"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, true
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane9.setViewportView(jTable_log);
            if (jTable_log.getColumnModel().getColumnCount() > 0) {
                jTable_log.getColumnModel().getColumn(0).setResizable(false);
            }

            jPanel_Quantities.setBackground(new java.awt.Color(217, 210, 210));
            jPanel_Quantities = new BarChartPanel();
            add(jPanel_modify); // Add it to the parent container

            javax.swing.GroupLayout jPanel_QuantitiesLayout = new javax.swing.GroupLayout(jPanel_Quantities);
            jPanel_Quantities.setLayout(jPanel_QuantitiesLayout);
            jPanel_QuantitiesLayout.setHorizontalGroup(
                jPanel_QuantitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 804, Short.MAX_VALUE)
            );
            jPanel_QuantitiesLayout.setVerticalGroup(
                jPanel_QuantitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 225, Short.MAX_VALUE)
            );

            jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
            jLabel5.setText("Changes Log");

            jButton_clearLog.setText("Clear Log");
            jButton_clearLog.setEnabled(false);
            jButton_clearLog.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_clearLogActionPerformed(evt);
                }
            });

            jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 2, 24)); // NOI18N
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("Lowest Quantities");

            jButton2.setFont(new java.awt.Font("Segoe UI Emoji", 2, 14)); // NOI18N
            jButton2.setText("Refresh");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(jButton2))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_clearLog))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jPanel_Quantities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(64, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jButton_clearLog))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jButton2))
                    .addGap(18, 18, 18)
                    .addComponent(jPanel_Quantities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(25, 25, 25))
            );

            jTabbedPane1.addTab("Reports", jPanel3);

            jPanel_modify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout jPanel_modifyLayout = new javax.swing.GroupLayout(jPanel_modify);
            jPanel_modify.setLayout(jPanel_modifyLayout);
            jPanel_modifyLayout.setHorizontalGroup(
                jPanel_modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            jPanel_modifyLayout.setVerticalGroup(
                jPanel_modifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 511, Short.MAX_VALUE)
            );

            jButton_refresh.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
            jButton_refresh.setText("Refresh");
            jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_refreshActionPerformed(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 2, 36)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Viewing Inventory");

            jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
            jButton1.setText("Push Updates");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jTextArea2.setEditable(false);
            jTextArea2.setColumns(20);
            jTextArea2.setFont(new java.awt.Font("Segoe UI Emoji", 2, 14)); // NOI18N
            jTextArea2.setLineWrap(true);
            jTextArea2.setRows(5);
            jTextArea2.setText("Modify items in the tables shown and click push updates to push them to the database, or refresh to get the latest data.");
            jTextArea2.setWrapStyleWord(true);
            jScrollPane2.setViewportView(jTextArea2);

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jPanel_modify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(17, 17, 17))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGap(36, 36, 36)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(0, 5, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jButton_refresh)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(37, 37, 37)))
                    .addComponent(jPanel_modify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(27, 27, 27))
            );

            jTabbedPane1.addTab("Modify", jPanel4);

            jPanel_add.setBackground(new java.awt.Color(102, 102, 102));

            jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

            jButton_AddItemType.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
            jButton_AddItemType.setText("Add");
            jButton_AddItemType.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_AddItemTypeActionPerformed(evt);
                }
            });

            jTextField_addItemTypeDescription.setToolTipText("");
            jTextField_addItemTypeDescription.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField_addItemTypeDescriptionActionPerformed(evt);
                }
            });

            jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
            jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel11.setText("Description");

            jTextField_addItemTypeName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

            jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
            jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel10.setText("Name");

            jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
            jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel9.setText("Add Item Type");

            jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_addItemTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jTextField_addItemTypeDescription)))
                    .addGap(75, 75, 75))
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(jButton_AddItemType)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel9)
                    .addGap(1, 1, 1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_addItemTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_addItemTypeDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jButton_AddItemType)
                    .addContainerGap(31, Short.MAX_VALUE))
            );

            jPanel_AddItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

            jTable_AddValues.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
            jTable_AddValues.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {"Name", ""},
                    {"Quantity", ""},
                    {"Price", ""},
                    {"Description", ""},
                    {"Shelf Life", ""},
                    {"Color", ""},
                    {"pfp", ""},
                    {"location", ""},
                    {"Item Type", ""}
                },
                new String [] {
                    "Property", "Value"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Object.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            jTable_AddValues.setRowHeight(30);
            jScrollPane5.setViewportView(jTable_AddValues);

            jButtton_AddItem.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
            jButtton_AddItem.setText("Add");
            jButtton_AddItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtton_AddItemActionPerformed(evt);
                }
            });

            jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
            jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel13.setText("Add Item");

            jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

            javax.swing.GroupLayout jPanel_AddItemLayout = new javax.swing.GroupLayout(jPanel_AddItem);
            jPanel_AddItem.setLayout(jPanel_AddItemLayout);
            jPanel_AddItemLayout.setHorizontalGroup(
                jPanel_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_AddItemLayout.createSequentialGroup()
                    .addGroup(jPanel_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_AddItemLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator2))
                        .addGroup(jPanel_AddItemLayout.createSequentialGroup()
                            .addGroup(jPanel_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_AddItemLayout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel_AddItemLayout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel_AddItemLayout.createSequentialGroup()
                                    .addGap(192, 192, 192)
                                    .addComponent(jButtton_AddItem)))
                            .addGap(0, 29, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel_AddItemLayout.setVerticalGroup(
                jPanel_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AddItemLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jButtton_AddItem)
                    .addContainerGap())
            );

            jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

            jTextArea1.setEditable(false);
            jTextArea1.setColumns(20);
            jTextArea1.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
            jTextArea1.setLineWrap(true);
            jTextArea1.setRows(5);
            jTextArea1.setText("This is the page to add an item or item type to your inventory.  If you add an item or item type that already exists in your  inventory, you will be notified.");
            jTextArea1.setWrapStyleWord(true);
            jScrollPane1.setViewportView(jTextArea1);

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap())
            );
            jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanel_addLayout = new javax.swing.GroupLayout(jPanel_add);
            jPanel_add.setLayout(jPanel_addLayout);
            jPanel_addLayout.setHorizontalGroup(
                jPanel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_addLayout.createSequentialGroup()
                    .addGroup(jPanel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel_AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE))
            );
            jPanel_addLayout.setVerticalGroup(
                jPanel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_addLayout.createSequentialGroup()
                    .addGroup(jPanel_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel_AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel_addLayout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(0, 236, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Add", jPanel_add);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButtton_AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtton_AddItemActionPerformed
        TableModel table = jTable_AddValues.getModel();
        // 2 Places where if the number of rows/data changes, the code will not work
        try {
            // Name, quantity, price, description, Shelf life, color, pfp, location
            // Adding the item
            String output = add.addItem(table.getValueAt(0, 1).toString(),
                Integer.parseInt(table.getValueAt(1, 1).toString()),
                Double.parseDouble(table.getValueAt(2, 1).toString()),
                table.getValueAt(3, 1).toString(),
                Integer.parseInt(table.getValueAt(4, 1).toString()),
                table.getValueAt(5, 1).toString(),
                null,
                table.getValueAt(7, 1).toString(),
                table.getValueAt(8, 1).toString());

            int index = output.indexOf("ERROR CODE:");
            String errorCode = "";
            if (index != -1)
            errorCode = output.substring(output.indexOf("ERROR CODE:") + 11);
            switch (errorCode){
                case "NAME-IN-USE" : createPopUp(new Object[]{"okay"}, "Name In Use", output, JOptionPane.CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, 0);
                case "ITEM-TYPE-DNE" : int choice = createPopUp(new Object[]{"Yes", "No"}, "Item Type Does Not Exist", output, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, 1);
                if (choice == 0) {
                    table.setValueAt("Misc", 8, 1);
                    jButtton_AddItemActionPerformed(evt);
                }
                case "" : createPopUp(new Object[]{"okay"}, "Successful Add", output, JOptionPane.CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, 0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtton_AddItemActionPerformed

    private void jTextField_addItemTypeDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addItemTypeDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addItemTypeDescriptionActionPerformed

    private void jButton_AddItemTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddItemTypeActionPerformed
        try {
            String output = add.addItemType(jTextField_addItemTypeName.getText(), jTextField_addItemTypeDescription.getText());

            int index = output.indexOf("ERROR CODE:");
            String errorCode = "";
            if (index != -1)
            errorCode = output.substring(output.indexOf("ERROR CODE:") + 12);
            switch (errorCode){
                case "NAME-IN-USE" : createPopUp(new Object[]{"okay"}, "Name In Use", output, JOptionPane.CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, 0);
                case "" : createPopUp(new Object[]{"okay"}, "Successful Add", output, JOptionPane.CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, 0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_AddItemTypeActionPerformed

    private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshActionPerformed
        try {
            updateLog();
        } catch (SQLException ex) {
            Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Getting data as a Hashmap of key being the item type name as a string
        // and the value being an arraylist of String arrays, each array holding
        // the stats/details about each item in that item type. Github test
        HashMap<String, ArrayList<String[]>> data = view.returnData();
        
        createBars(data);
        //localData = data;
        
        // The panel should not just be the addPanel but whichever tab you are on.
        JPanel holderPanelRemove = new JPanel();
        holderPanelRemove.setLayout(new BoxLayout(holderPanelRemove, BoxLayout.Y_AXIS));
            
        jPanel_modify.removeAll();
        
        int sectionY = 1;
        for (String key : data.keySet()) { // Github test
            // Creating an empty table and model
            DefaultTableModel model = new DefaultTableModel(new String[]{"Name", "Quantity", "Price", "Description", "Shelf Life", "Color", "PFP", "Locaiton", "Item Type", "Item Type ID", "itemID"}, 0) {
                // Specify which columns are editable
                @Override
                public boolean isCellEditable(int row, int column) {
                    // Make the "Age" column (column index 1) uneditable
                    return column != 10;
                }
            };
            
            // Adding rows to the table, number of rows determined by how large
            // the arraylist for that item type is, and each row filled with the
            // arrays of strings in the arraylist. 
            ArrayList<String[]> ITData = data.get(key);
            // If no items for an itemType, adds a row of nothing it it
            if (!ITData.isEmpty()) {
                for (String[] itemData : data.get(key))
                {
                    addRow(model, itemData);
                }
            }
            else
                addRow(model, new String[]{"No Items Yet", "", "", "", "", "", "", "", "", "", ""});
            
            
            ///////// ACTUALLY ADDING THE TABLE TO THE CHIEF CONTAINER, jPanel_addPanel
            
            
            addLabel(holderPanelRemove, new Font("Times New Roman", Font.PLAIN, 20), key, 10);
            
            
            addTable(model, holderPanelRemove, 100);
            
            sectionY++;
        }
        
        // Creating the JScrollPane that will hold the holderPanel
        JScrollPane mainScrollPane = new JScrollPane(holderPanelRemove);
        mainScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        
        updateTablesOnPanels(jPanel_modify, mainScrollPane, BorderLayout.CENTER);
        
        
    }//GEN-LAST:event_jButton_refreshActionPerformed

    private void createBars(HashMap<String, ArrayList<String[]>> data) {
        ArrayList<Integer> vals = new ArrayList<>();
        ArrayList<String> names = new ArrayList<>();
        for (String s : data.keySet())
        {
                for (String[] arrays : data.get(s))
                {
                    vals.add(Integer.valueOf(arrays[1]));
                    names.add(arrays[0]);
                }
        }
        
        for (int i = 0; i < vals.size() - 1; i++) {
            for (int j = 0; j < vals.size() - 1 - i; j++) {
                if (vals.get(j) > vals.get(j + 1)) {
                    // Swap the elements
                    int temp = vals.get(j);
                    vals.set(j, vals.get(j + 1));
                    vals.set(j + 1, temp);
                    String tempS = names.get(j);
                    names.set(j, names.get(j + 1));
                    names.set(j + 1, tempS);
                }
            }
        }
        if (jPanel_Quantities instanceof BarChartPanel) {
            BarChartPanel barChartPanel = (BarChartPanel) jPanel_Quantities;
            barChartPanel.setVals(vals);
            barChartPanel.setNames(names);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String output = change.changeItems();
            if (output.contains("CHANGE"))
            {
                output = output.substring(6);
                createPopUp(new Object[]{"okay"}, "DB Conlict", output + "\n please refresh before pushing", JOptionPane.CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, 0);
            }
            else
            {
                createPopUp(new Object[]{"okay"}, "Successful Push", "All changes pushed successfully", JOptionPane.CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, 0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_clearLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearLogActionPerformed
        //  change
    }//GEN-LAST:event_jButton_clearLogActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton_refreshActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private int createPopUp(Object[] options, String title, String message, int optionType, int messageType, int initialVal) {
        
        int n = JOptionPane.showOptionDialog(null,
            message,
            title,
            optionType,
            messageType,
            null,
            options,
            options[initialVal]);
        
        return n;
    }
    
    
    private HashMap<String, ArrayList<String[]>> testData() {
        HashMap<String, ArrayList<String[]>> data = new HashMap<>();
        ArrayList<String[]> dessert = new ArrayList<>();
        dessert.add(new String[]{"chocolate", "3", "6", "yum", "4", "black", "", "counter", "desserts"});
        dessert.add(new String[]{"ice cream", "1", "1", "yum", "4", "white", "", "freezer", "desserts"});
        dessert.add(new String[]{"brownie", "1", "1", "yum", "4", "white", "", "freezer", "desserts"});
        dessert.add(new String[]{"cookie", "1", "1", "yum", "4", "white", "", "freezer", "desserts"});
        dessert.add(new String[]{"anything else", "1", "1", "yum", "4", "white", "", "freezer", "desserts"});
        data.put("desserts", dessert);
        ArrayList<String[]> food = new ArrayList<>();
        data.put("drinks", new ArrayList<>());
        food.add(new String[]{"pizza", "1", "1", "yum", "4", "white", "", "microwave", "food"});
        data.put("food", food);
        data.put("misc", new ArrayList<>());
        return data;
    }
    
    private void updateTablesOnPanels(JPanel jPanel, Component parentPane, String constraint) {
        JScrollPane mainScrollPane = new JScrollPane(parentPane);
        jPanel.setLayout(new BorderLayout());
        jPanel.add(mainScrollPane, constraint);
        jPanel.update(jPanel.getGraphics());
        jPanel.revalidate();
    }
    
    
    /////////////////////////////////////////////////////////////////////////////
    private void updateLog() throws SQLException {
        ArrayList<String[]> log = view.getDBLog();
        int index = 0;
        DefaultTableModel model = (DefaultTableModel) jTable_log.getModel();
        for (String[] val : log) {
            model.addRow(new String[]{val[0], val[1]});
            index++;
        }
        jTable_log.updateUI();
    }
    
    /////////////////////////////////////////////////////////////////////////////
    private void addTable(DefaultTableModel model, JPanel panel, int buffer) {
        JTable table = new JTable(model);
        JScrollPane tableScrollPane = new JScrollPane(table);
        
        JTableHeader header = table.getTableHeader();
        int headerHeight = 0;
        //int headerHeight = header.getHeight();
        System.out.println("height " + headerHeight);
        
        header.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // This method is called when the JTableHeader is resized
                int headerHeight = header.getHeight();
                table.setPreferredSize(new Dimension(tableScrollPane.getWidth(), (model.getRowCount()) * table.getRowHeight() + headerHeight + 10));
                tableScrollPane.setPreferredSize(new Dimension(tableScrollPane.getWidth(), (model.getRowCount()) * table.getRowHeight() + headerHeight + 10));
     
                System.out.println("Header Height after resize: " + headerHeight);
                System.out.println("row height: " + table.getRowHeight());
            }
        });
        
        // Add selection listener
            table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                int previousSelectedRow = -1;
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    int selectedRow = table.getSelectedRow();
                    
                    if (!e.getValueIsAdjusting()) {
                        if (selectedRow != -1) {
                            addSelected(Integer.parseInt(table.getValueAt(selectedRow, 9).toString()),
                table.getValueAt(selectedRow, 0).toString(),
                Integer.parseInt(table.getValueAt(selectedRow, 1).toString()),
                Double.parseDouble(table.getValueAt(selectedRow, 2).toString()),
                table.getValueAt(selectedRow, 3).toString(),
                Integer.parseInt(table.getValueAt(selectedRow, 4).toString()),
                table.getValueAt(selectedRow, 5).toString(),
                null,
                table.getValueAt(selectedRow, 6).toString(),
                Integer.parseInt(table.getValueAt(selectedRow, 9).toString()));
                        }
                    }
                    if ((selectedRow == -1 || selectedRow != previousSelectedRow)  && previousSelectedRow != -1) {
                        checkChange(Integer.parseInt(table.getValueAt(previousSelectedRow, 9).toString()),
                table.getValueAt(previousSelectedRow, 0).toString(),
                Integer.parseInt(table.getValueAt(previousSelectedRow, 1).toString()),
                Double.parseDouble(table.getValueAt(previousSelectedRow, 2).toString()),
                table.getValueAt(previousSelectedRow, 3).toString(),
                Integer.parseInt(table.getValueAt(previousSelectedRow, 4).toString()),
                table.getValueAt(previousSelectedRow, 5).toString(),
                null,
                table.getValueAt(previousSelectedRow, 6).toString(),
                Integer.parseInt(table.getValueAt(previousSelectedRow, 9).toString()));
                    }
                    previousSelectedRow = selectedRow;
                }
            });

        
        System.out.println("after the compnent listeneer");
        
        panel.add(tableScrollPane);
        panel.add(Box.createRigidArea(new Dimension(0, buffer)));
        panel.revalidate();
        
    }
    
    private void addLabel(JPanel panel, Font font, String text, int height) {
        JLabel label = new JLabel();
        label.setFont(font);
        label.setText(text);
        label.setAlignmentX(Component.CENTER_ALIGNMENT);
        if (panel != null)
        {
            panel.add(label);
            panel.add(Box.createRigidArea(new Dimension(0, height)));
        }
    }
    
    private void addSelected(int id, String itemName, int quantity, double price, String itemDescription, int shelfLife, String color, String pfp, String location, int itemTypeID) {
        change.addToChangeID(id, itemName, quantity, price, itemDescription, shelfLife, color, pfp, location, itemTypeID);
    }
    
    private void checkChange(int id, String itemName, int quantity, double price, String itemDescription, int shelfLife, String color, String pfp, String location, int itemTypeID) {
        change.checkChange(id, itemName, quantity, price, itemDescription, shelfLife, color, pfp, location, itemTypeID);
    }
    
    private void addRow(DefaultTableModel model, String[] data) {
        model.addRow(data);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InventoryGUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(InventoryGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_AddItemType;
    private javax.swing.JButton jButton_clearLog;
    private javax.swing.JButton jButton_refresh;
    private javax.swing.JButton jButtton_AddItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_AddItem;
    private javax.swing.JPanel jPanel_Quantities;
    private javax.swing.JPanel jPanel_add;
    private javax.swing.JPanel jPanel_modify;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_AddValues;
    private javax.swing.JTable jTable_log;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField_addItemTypeDescription;
    private javax.swing.JTextField jTextField_addItemTypeName;
    // End of variables declaration//GEN-END:variables
}
